/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLinksNewRouteImport } from './routes/_authenticated/links.new'
import { Route as AuthenticatedLinksSlugRouteImport } from './routes/_authenticated/links.$slug'
import { Route as ApiPublicWebhooksTelegramSlugRouteImport } from './routes/api/public/webhooks/telegram.$slug'
import { Route as ApiPublicWebhooksDiscordSlugRouteImport } from './routes/api/public/webhooks/discord.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksNewRoute = AuthenticatedLinksNewRouteImport.update({
  id: '/links/new',
  path: '/links/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksSlugRoute = AuthenticatedLinksSlugRouteImport.update({
  id: '/links/$slug',
  path: '/links/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksTelegramSlugRoute =
  ApiPublicWebhooksTelegramSlugRouteImport.update({
    id: '/api/public/webhooks/telegram/$slug',
    path: '/api/public/webhooks/telegram/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksDiscordSlugRoute =
  ApiPublicWebhooksDiscordSlugRouteImport.update({
    id: '/api/public/webhooks/discord/$slug',
    path: '/api/public/webhooks/discord/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/r/$slug': typeof RSlugRoute
  '/links/$slug': typeof AuthenticatedLinksSlugRoute
  '/links/new': typeof AuthenticatedLinksNewRoute
  '/api/public/webhooks/discord/$slug': typeof ApiPublicWebhooksDiscordSlugRoute
  '/api/public/webhooks/telegram/$slug': typeof ApiPublicWebhooksTelegramSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/r/$slug': typeof RSlugRoute
  '/links/$slug': typeof AuthenticatedLinksSlugRoute
  '/links/new': typeof AuthenticatedLinksNewRoute
  '/api/public/webhooks/discord/$slug': typeof ApiPublicWebhooksDiscordSlugRoute
  '/api/public/webhooks/telegram/$slug': typeof ApiPublicWebhooksTelegramSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/links/$slug': typeof AuthenticatedLinksSlugRoute
  '/_authenticated/links/new': typeof AuthenticatedLinksNewRoute
  '/api/public/webhooks/discord/$slug': typeof ApiPublicWebhooksDiscordSlugRoute
  '/api/public/webhooks/telegram/$slug': typeof ApiPublicWebhooksTelegramSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/team'
    | '/r/$slug'
    | '/links/$slug'
    | '/links/new'
    | '/api/public/webhooks/discord/$slug'
    | '/api/public/webhooks/telegram/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/team'
    | '/r/$slug'
    | '/links/$slug'
    | '/links/new'
    | '/api/public/webhooks/discord/$slug'
    | '/api/public/webhooks/telegram/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/team'
    | '/r/$slug'
    | '/_authenticated/links/$slug'
    | '/_authenticated/links/new'
    | '/api/public/webhooks/discord/$slug'
    | '/api/public/webhooks/telegram/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicWebhooksDiscordSlugRoute: typeof ApiPublicWebhooksDiscordSlugRoute
  ApiPublicWebhooksTelegramSlugRoute: typeof ApiPublicWebhooksTelegramSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links/new': {
      id: '/_authenticated/links/new'
      path: '/links/new'
      fullPath: '/links/new'
      preLoaderRoute: typeof AuthenticatedLinksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links/$slug': {
      id: '/_authenticated/links/$slug'
      path: '/links/$slug'
      fullPath: '/links/$slug'
      preLoaderRoute: typeof AuthenticatedLinksSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/telegram/$slug': {
      id: '/api/public/webhooks/telegram/$slug'
      path: '/api/public/webhooks/telegram/$slug'
      fullPath: '/api/public/webhooks/telegram/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/discord/$slug': {
      id: '/api/public/webhooks/discord/$slug'
      path: '/api/public/webhooks/discord/$slug'
      fullPath: '/api/public/webhooks/discord/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksDiscordSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedLinksSlugRoute: typeof AuthenticatedLinksSlugRoute
  AuthenticatedLinksNewRoute: typeof AuthenticatedLinksNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedLinksSlugRoute: AuthenticatedLinksSlugRoute,
  AuthenticatedLinksNewRoute: AuthenticatedLinksNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicWebhooksDiscordSlugRoute: ApiPublicWebhooksDiscordSlugRoute,
  ApiPublicWebhooksTelegramSlugRoute: ApiPublicWebhooksTelegramSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
